# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- script: curl https://api-scanner.tinfoilsecurity.com/api/v1/organizations -X GET -H 'Authorization:Token token=0B2FD224A4A9E2D5E916883806C1F887899C811B5EBCEDB78450FBE5F3215CA4, access_key=FDBCDB5570611D0204EAC92698D5C3577955C3EFC20550755467AF4005071B62'